github:
  host: github.com          # change to your-firm.github.com for enterprise
  org: patternic       # GitHub org or user that owns the repos
  clone_protocol: https      # ssh | https
  repos:
    - https://github.com/patterninc/finczar.git
    - https://github.com/patterninc/amaczar.git