github:
  host: github.com          # change to your-firm.github.com for enterprise
  org: patterninc
  discipline: data-engineering       # GitHub org or user that owns the repos
  clone_protocol: https      # ssh | https
  repos:
    - https://github.com/patterninc/data-airflowhttps://github.com/patterninc/data-airflow 
    - https://github.com/patterninc/heimdall
    - https://github.com/patterninc/caterpillar 
    - https://github.com/patterninc/playwright-executor 
    - https://github.com/patterninc/playwright-server 

    